version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
    app:
        image: feral113/blog:latest
        ports:
            - "5050:5050"
        depends_on:
            - db