version: '3'
services:
    db:
        image: postgres
        networks:
            - mynetwork
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
    app:
        image: feral113/blog:latest
        networks:
            - mynetwork
        ports:
            - "5050:443"
        depends_on:
            - db

networks:
    mynetwork:
