name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and run Gulp build
        run: |
          npm install
          npm run build

      - name: Create certificates
        run: |
          mkdir Server/build/certificates
          touch Server/build/certificates/certificate.pem
          touch Server/build/certificates/privateKey.key

      - name: Write data in certificates
        run: |
          echo "${{secrets.SSL_CERTIFICATE}}" | cat >> Server/build/certificates/certificate.pem
          echo "${{secrets.SSL_PRIVATE_KEY}}" | cat >> Server/build/certificates/privateKey.key

      - name: Build Docker image
        run: docker build . --file Dockerfile -t feral113/blog:latest

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push feral113/blog:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /home/${{secrets.SSH_USERNAME}}/Blog && git pull && docker-compose up -d'