name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Clean up
      run: docker rmi my-image-name:$(date +%s)

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Clean up
      run: docker system prune -f
