name: Deploy to GitHub Pages

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
  deploy:
    environment:
        name: github-pages
        url: http://github.ra334.blog.com

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: docker compose up
        wait-on: http://localhost
